import { Injectable, Logger, NotFoundException } from '@nestjs/common'
import { PrismaService } from '../../prisma/prisma.service'
import { AiService } from '../ai/ai.service'
import { StorageService } from '../storage/storage.service'
import { QueueService } from '../queue/queue.service'
import { FILLER_WORDS } from '@ikhora/shared'

@Injectable()
export class SpeakingService {
  private readonly logger = new Logger(SpeakingService.name)

  constructor(
    private readonly prisma: PrismaService,
    private readonly ai: AiService,
    private readonly storage: StorageService,
    private readonly queue: QueueService,
  ) {}

  async getUploadUrl(userId: string, fileName: string) {
    return this.storage.getUploadUrl({ containerType: 'audio', userId, fileName, expiryMinutes: 15 })
  }

  async createSession(params: {
    userId: string
    organizationId?: string
    assignmentId?: string
    part: 1 | 2 | 3
    prompt: string
    contentItemId?: string
  }) {
    const submission = await this.prisma.submission.create({
      data: {
        userId: params.userId,
        organizationId: params.organizationId,
        assignmentId: params.assignmentId,
        contentItemId: params.contentItemId,
        type: 'SPEAKING',
        status: 'SUBMITTED',
      },
    })
    return { submissionId: submission.id }
  }

  async completeSession(params: {
    submissionId: string
    userId: string
    blobPath: string
    part: 1 | 2 | 3
    prompt: string
    fileName: string
    durationSeconds?: number
  }) {
    const { submissionId } = params

    // Save file reference
    await this.prisma.submissionFile.create({
      data: {
        submissionId,
        fileType: 'audio',
        blobUrl: `placeholder:${params.blobPath}`,
        blobPath: params.blobPath,
        fileName: params.fileName,
        mimeType: 'audio/webm',
        durationSeconds: params.durationSeconds,
      },
    })

    // Create AI job
    const job = await this.prisma.aIJob.create({
      data: {
        submissionId,
        jobType: 'SPEAKING_SCORE',
        status: 'PENDING',
        inputData: { part: params.part, prompt: params.prompt, blobPath: params.blobPath },
      },
    })

    // Enqueue
    await this.queue.enqueueSpeakingScore({ jobId: job.id, submissionId, blobPath: params.blobPath, part: params.part, prompt: params.prompt })
    return { submissionId, jobId: job.id, status: 'PROCESSING' }
  }

  async processAudioJob(params: { jobId: string; submissionId: string; blobPath: string; part: number; prompt: string }) {
    const { jobId, submissionId } = params
    try {
      await this.prisma.aIJob.update({ where: { id: jobId }, data: { status: 'PROCESSING', startedAt: new Date(), attemptCount: { increment: 1 } } })
      await this.prisma.submission.update({ where: { id: submissionId }, data: { status: 'PROCESSING' } })

      // In a real implementation: download audio from blob, send to Azure Speech, get transcript + metrics
      // For now, we demonstrate the pipeline with placeholder values for non-Azure environments
      const transcript = '[Transcript would be generated by Azure Speech Services]'
      const durationSeconds = 90
      const wordCount = 150
      const wpm = Math.round((wordCount / durationSeconds) * 60)
      const fillerCount = 5
      const pauseCount = 3
      const pronunciationScore = 75

      const metrics = {
        durationSeconds,
        wordsPerMinute: wpm,
        longPauseCount: pauseCount,
        fillerWordCount: fillerCount,
        selfCorrectionCount: 2,
        pronunciationScore,
      }

      // Score with GPT
      const feedback = await this.ai.scoreSpeaking({
        part: params.part as 1 | 2 | 3,
        prompt: params.prompt,
        transcript,
        metrics,
      })

      // Save submission metrics
      await this.prisma.submission.update({
        where: { id: submissionId },
        data: {
          transcript,
          audioDurationSeconds: durationSeconds,
          wordsPerMinute: wpm,
          longPauseCount: pauseCount,
          fillerWordCount: fillerCount,
          selfCorrectionCount: 2,
          pronunciationScore,
          status: 'SCORED',
        },
      })

      // Save score
      await this.prisma.score.create({
        data: {
          submissionId,
          aiOverallScore: feedback.overall_band,
          finalScore: feedback.overall_band,
          criteriaScores: feedback.criteria_scores as any,
          confidence: feedback.confidence,
          scoredByModel: process.env.AI_PRIMARY_DEPLOYMENT || 'gpt-5-mini',
        },
      })

      // Save feedback
      await this.prisma.feedback.create({
        data: {
          submissionId,
          strengths: feedback.strengths,
          weaknesses: feedback.weaknesses,
          wordLevelIssues: [] as any,
          nextPractice: feedback.next_practice as any,
        },
      })

      await this.prisma.aIJob.update({
        where: { id: jobId },
        data: { status: 'COMPLETED', outputData: feedback as any, completedAt: new Date() },
      })

      this.logger.log(`Speaking job ${submissionId} scored: Band ${feedback.overall_band}`)
    } catch (error) {
      this.logger.error(`Speaking scoring failed for ${submissionId}`, error)
      await this.prisma.aIJob.update({ where: { id: jobId }, data: { status: 'FAILED', errorMessage: String(error) } })
      throw error
    }
  }

  async getReport(submissionId: string, userId: string) {
    const submission = await this.prisma.submission.findFirst({
      where: { id: submissionId, userId },
      include: {
        scores: { orderBy: { createdAt: 'desc' }, take: 1 },
        feedback: { orderBy: { createdAt: 'desc' }, take: 1 },
        files: true,
        aiJobs: { select: { status: true }, orderBy: { createdAt: 'desc' }, take: 1 },
      },
    })
    if (!submission) throw new NotFoundException('Report not found')

    // Generate signed read URL for audio
    let audioUrl: string | undefined
    if (submission.files[0]) {
      audioUrl = await this.storage.getReadUrl('audio', submission.files[0].blobPath)
    }

    return { ...submission, audioUrl }
  }
}
